import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/sonner";
import { loraFont, soraFont } from "./fonts";
import { BreadcrumbNavigation } from "@/components/NavBar/BreadcrumbNavigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${loraFont.variable} ${soraFont.variable} antialiased`}
      >
        <Toaster />
        <Providers>
          <main className="min-h-screen flex flex-col">
            <BreadcrumbNavigation />
            <div className="flex-1">
              {children}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
